### ISSUE TITLE
Status in Header

### ISSUE THREAD

**Issue by Nakort** [prerender/prerender_rails#17]
Hey guys, I am getting an error after prerendering my app in Rack::Lint, the Header has the status key in it, and I am getting

<code> 
Rack::Lint::LintError at </path> header must not contain Status
</code>

This happens here:

https://github.com/rack/rack/blob/master/lib/rack/lint.rb#L639

Wasn't sure whether to report this issue here of the prerender repo.

Thanks!

**Comment by thoop** [comment]
Thanks for letting us know! Can you give me any more info so that I can reproduce it? Does it happen on all of your pages? Do you know what version of rack you are using?

**Comment by wtfiwtz** [comment]
+1

Ruby 2.1.5, Rails 4.2.1
unicorn (4.8.3)
prerender_rails (1.1.2)

github.com/prerender/prerender @ 017d275e

Rails log below:
```
I, [2015-06-27T15:37:36.143136 #59008]  INFO -- : worker=1 ready
I, [2015-06-27T15:37:36.177222 #59009]  INFO -- : worker=2 ready
I, [2015-06-27T15:37:36.195378 #59007]  INFO -- : worker=0 ready
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET / HTTP/1.1" 200 - 1.3636
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /jquery/jquery.js?body=1 HTTP/1.1" 200 247598 0.0446
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /jquery.js?body=1 HTTP/1.1" 200 - 0.0444
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /jquery_ujs.js?body=1 HTTP/1.1" 200 18201 0.0480
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular/angular.js?body=1 HTTP/1.1" 200 960562 0.0473
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular.js?body=1 HTTP/1.1" 200 - 0.0338
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /application.css?body=1 HTTP/1.1" 200 786768 0.1875
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-resource/angular-resource.js?body=1 HTTP/1.1" 200 26778 0.0340
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-resource.js?body=1 HTTP/1.1" 200 - 0.0430
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-route/angular-route.js?body=1 HTTP/1.1" 200 35759 0.0425
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-route.js?body=1 HTTP/1.1" 200 - 0.0347
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-sanitize/angular-sanitize.js?body=1 HTTP/1.1" 200 24357 0.0314
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-sanitize.js?body=1 HTTP/1.1" 200 - 0.0350
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-touch/angular-touch.js?body=1 HTTP/1.1" 200 22882 0.0299
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-touch.js?body=1 HTTP/1.1" 200 - 0.0325
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-animate/angular-animate.js?body=1 HTTP/1.1" 200 104239 0.0312
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /checklist-model/checklist-model.js?body=1 HTTP/1.1" 200 3071 0.0305
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-animate.js?body=1 HTTP/1.1" 200 - 0.0349
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /ng-resources.js?body=1 HTTP/1.1" 200 17679 0.0349
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /checklist-model.js?body=1 HTTP/1.1" 200 - 0.0391
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /filters.js?body=1 HTTP/1.1" 200 2374 0.0282
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-ui-bootstrap-tpls.js?body=1 HTTP/1.1" 200 142975 0.0337
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /users.js?body=1 HTTP/1.1" 200 1516 0.0295
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /associations.js?body=1 HTTP/1.1" 200 1456 0.0295
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /clubs.js?body=1 HTTP/1.1" 200 7909 0.0317
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /teams.js?body=1 HTTP/1.1" 200 2449 0.0283
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /profile.js?body=1 HTTP/1.1" 200 5965 0.0333
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /dashboard.js?body=1 HTTP/1.1" 200 23323 0.0342
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /ng-routes.js?body=1 HTTP/1.1" 200 6353 0.0323
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /articles.js?body=1 HTTP/1.1" 200 3110 0.0414
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /bootstrap.js?body=1 HTTP/1.1" 200 67547 0.0354
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /modernizr-ra/modernizr.js?body=1 HTTP/1.1" 200 51352 0.0329
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /modernizr-ra.js?body=1 HTTP/1.1" 200 - 0.0347
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angularjs-file-upload.js?body=1 HTTP/1.1" 200 49388 0.1237
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /easypie/angular.easypiechart.js?body=1 HTTP/1.1" 200 9781 0.0316
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-vertilize.js?body=1 HTTP/1.1" 200 2903 0.0274
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /lodash/lodash.compat.js?body=1 HTTP/1.1" 200 244132 0.0344
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /lodash.js?body=1 HTTP/1.1" 200 - 0.0313
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-google-maps.js?body=1 HTTP/1.1" 200 - 0.0309
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-google-maps/angular-google-maps.js?body=1 HTTP/1.1" 200 489778 0.0399
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-truncate-asset/truncate.js?body=1 HTTP/1.1" 200 1295 0.0316
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular-truncate-asset.js?body=1 HTTP/1.1" 200 - 0.0318
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /angular.country-select.js?body=1 HTTP/1.1" 200 4707 0.0288
127.0.0.1 - - [27/Jun/2015:15:37:39 +1000] "GET /animate.css HTTP/1.1" 200 81529 0.0394
127.0.0.1 - - [27/Jun/2015:15:37:40 +1000] "GET /application.js?body=1 HTTP/1.1" 200 31 0.0896
127.0.0.1 - - [27/Jun/2015:15:37:40 +1000] "GET /dashboard/dashboard.html HTTP/1.1" 200 528 0.0285
127.0.0.1 - - [27/Jun/2015:15:37:40 +1000] "GET /users/1.json HTTP/1.1" 302 - 0.0454
127.0.0.1 - - [27/Jun/2015:15:37:40 +1000] "GET /users/current.json HTTP/1.1" 302 - 0.0594
127.0.0.1 - - [27/Jun/2015:15:37:40 +1000] "GET /dashboard/_navigation.html HTTP/1.1" 200 4046 0.0305
127.0.0.1 - - [27/Jun/2015:15:37:40 +1000] "GET /dashboard/_profile.html HTTP/1.1" 200 2865 0.0353
127.0.0.1 - - [27/Jun/2015:15:37:40 +1000] "GET /dashboard/_player-stats.html HTTP/1.1" 200 4466 0.0444
127.0.0.1 - - [27/Jun/2015:15:37:40 +1000] "GET /dashboard/_games.html HTTP/1.1" 200 8598 0.0386
127.0.0.1 - - [27/Jun/2015:15:37:40 +1000] "GET /dashboard/_footer.html HTTP/1.1" 200 530 0.0430
127.0.0.1 - - [27/Jun/2015:15:37:41 +1000] "GET /login HTTP/1.1" 200 - 0.9402
127.0.0.1 - - [27/Jun/2015:15:37:41 +1000] "GET /player_profiles/_avatar.html HTTP/1.1" 200 220 0.0336
127.0.0.1 - - [27/Jun/2015:15:37:41 +1000] "GET /bootstrap/glyphicons-halflings-regular.woff HTTP/1.1" 200 23424 0.0365
127.0.0.1 - - [27/Jun/2015:15:37:41 +1000] "GET /fonts/ElegantIcons.woff HTTP/1.1" 200 63664 0.0455
127.0.0.1 - - [27/Jun/2015:15:37:41 +1000] "GET /fonts/ct-icon-font.woff?d2z26c HTTP/1.1" 200 14260 0.0387
127.0.0.1 - - [27/Jun/2015:15:37:41 +1000] "GET /login HTTP/1.1" 200 - 1.3635
Rack::Lint::LintError: header must not contain Status
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/rack-1.6.1/lib/rack/lint.rb:20:in `assert'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/rack-1.6.1/lib/rack/lint.rb:639:in `block in check_headers'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/rack-1.6.1/lib/rack/utils.rb:483:in `block in each'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/rack-1.6.1/lib/rack/utils.rb:482:in `each'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/rack-1.6.1/lib/rack/utils.rb:482:in `each'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/rack-1.6.1/lib/rack/lint.rb:629:in `check_headers'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/rack-1.6.1/lib/rack/lint.rb:53:in `_call'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/rack-1.6.1/lib/rack/lint.rb:37:in `call'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/rack-1.6.1/lib/rack/showexceptions.rb:24:in `call'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/rack-1.6.1/lib/rack/commonlogger.rb:33:in `call'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/rack-1.6.1/lib/rack/chunked.rb:54:in `call'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/rack-1.6.1/lib/rack/content_length.rb:15:in `call'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in `process_client'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/bin/unicorn:23:in `load'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/bin/unicorn:23:in `<main>'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	/Users/wtfiwtz/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
127.0.0.1 - - [27/Jun/2015:15:37:44 +1000] "GET /?_escaped_fragment_=/users/1/dashboard HTTP/1.1" 500 122571 8.1491
```

**Comment by wtfiwtz** [comment]
Strangely I restarted Unicorn with `binding.pry if key.downcase.eql?('status')` on the relevant line of Rack's lint.rb and the problem disappeared. 

This URL:
http://localhost:8080/?_escaped_fragment_=/users/1/dashboard

... was redirected to this:
http://localhost:8080/?_escaped_fragment_=/users/1/dashboard#!/users/1/dashboard

So if that is normal, maybe its just a transient thing.

I'm doing my testing on Mac OS X 10.10.3

**Comment by wtfiwtz** [comment]
Here's the response from prerender at the end of `build_rack_response_from_prerender` - you can see the `status` entry in `@header`:

```
Prerender response: #<Rack::Response:0x007fa85c0a08a0 @status=200, @header={"date"=>"Sat, 27 Jun 2015 06:15:15 GMT", "status"=>"200 OK", "connection"=>"close", "x-frame-options"=>"SAMEORIGIN", "x-xss-protection"=>"1; mode=block", "x-content-type-options"=>"nosniff", "content-type"=>"text/html;charset=UTF-8", "etag"=>"W/\"40ae98093f5913da9758db024f61029a\"", "cache-control"=>"max-age=0, private, must-revalidate", "set-cookie"=>"XSRF-TOKEN=nVCk%2BP9CUzQ%2BBdAH75vzbRn4c2L%2Bz%2FXk28H%2FuDxRKDv9ZVkSAzt3iqIqGlrSwPbop%2B0hI44I7Y1oH%2BLKfluKCA%3D%3D; path=/_ctbe_session=UjBBeVQ5MWorOWh0VXdrNUNNSTZKbHVHY1ZubEZxeDNQZ3cyRDRxRXZ0cDEwdjd4bVhIZnUwdUhwSVJDUlJCbExQUVpGZXNPRThJbUlyQnBaenFPZU85Nm5aTnJKSmFyem40aUFjdVZOWllIa2hiQlc2dFVKSHFzYWZFVGU0VitlU3RwcFhuNXpQNWZvWkwrbUhMWXhnPT0tLWpxMTB2MVJGKytPdUlnYnhHaF
```

In Rack's response.rb I added this `header.delete 'status'` and it got rid of the issue:
```ruby
    def finish(&block)
      @block = block

      header.delete 'status'
      if [204, 205, 304].include?(status.to_i)
        header.delete CONTENT_TYPE
        header.delete CONTENT_LENGTH
        close
        [status.to_i, header, []]
      else
        [status.to_i, header, BodyProxy.new(self){}]
      end
    end
```

However, I probably can't do the same from the `prerender_rails` gem as `response.header` is `attr_reader` :(

**Comment by michaelnatkin** [comment]
@thoop i'm experiencing this too, using foreman to run unicorn with rails. Any suggestions?

**Comment by thoop** [comment]
We aren't explicitly adding a "status" header if you look in our code. We're just using a Rack response. Are you sending back status as a header in the response from your server?

**Comment by michaelnatkin** [comment]
It is coming back from phantom, I can see it right in the place where you build the prerender response, running locally against the prerender server.

**Comment by thoop** [comment]
Can you see it when you access the Prerender server directly with the same URL from your browser? The Prerender server returns whatever headers your server returns so it sounds like you are returning the status header in your response to the Prerender server.

**Comment by michaelnatkin** [comment]
@thoop I didn't end up checking but did find a good workaround, add this when configuring the middleware:

```
    config.middleware.insert_before ActionDispatch::Static, 'Rack::Prerender', {
        build_rack_response_from_prerender: lambda { |response, unused| response.header.delete('Status') }
    }
```

**Comment by thoop** [comment]
Hmm, interesting. Thanks for letting me know.

**Comment by thoop** [comment]
Looks like there are some workarounds here and we've been unable to reproduce so going to mark this issue as closed. Please feel free to reopen with any more info if someone runs into this issue again.
